packages/button/package.json
packages/button/src/Button.tsx
packages/button/src/index.ts
packages/button/src/types.ts
packages/button/src/utils.ts
yarn.lock

chore(button): init

---

packages/button/package.json

fix(button): fix import filetype

---

packages/utils/package.json
packages/utils/src/getElementSize.ts
packages/utils/src/index.ts
packages/utils/src/useWindowSize.ts
packages/utils/tsconfig.json

feat(utils): init

---

packages/button/src/Button.tsx
packages/button/src/types.ts
packages/button/tsconfig.json

refactor(button): remove typography

---

.github/workflows/check.yml
packages/carousel/package.json
packages/carousel/src/Carousel.tsx
packages/carousel/src/SlideButton.tsx
packages/carousel/src/index.ts
packages/carousel/tsconfig.json
yarn.lock

affects: @atlantis-lab/carousel

feat(carousel): init carousel

---

packages/button/src/Button.tsx
packages/carousel/package.json
packages/carousel/src/Carousel.tsx
packages/icons/package.json
packages/icons/tsconfig.compile.json

affects: @atlantis-lab/button, @atlantis-lab/carousel

refactor(packages): add typography in button and steps in carousel

---

packages/button/src/Button.tsx

refactor(button): add normal backgroundColor and text color inherit

---

.github/workflows/check.yml
package.json
packages/slideshow/package.json
packages/slideshow/src/Slices.tsx
packages/slideshow/src/Slideshow.tsx
packages/slideshow/src/index.ts
packages/slideshow/tsconfig.json

affects: @atlantis-lab/slideshow

feat(slideshow): slideshow init

---

packages/button/src/Button.tsx

refactor(button): add hoverBackgroundColor

---

packages/hamburger/package.json
packages/hamburger/src/Hamburger.tsx
packages/hamburger/src/index.ts
packages/hamburger/src/types.ts
packages/hamburger/tsconfig.json

affects: @atlantis-lab/hamburger

feat: hamburger init

---

.github/workflows/check.yml
.github/workflows/publish.yml
packages/button/tsconfig.json
packages/carousel/tsconfig.json
packages/hamburger/tsconfig.json
packages/icons/tsconfig.json
packages/slideshow/tsconfig.json
packages/utils/tsconfig.json
tsconfig.json

affects: @atlantis-lab/button, @atlantis-lab/carousel, @atlantis-lab/hamburger, @atlantis-lab/icons,
@atlantis-lab/slideshow, @atlantis-lab/utils

chore: specify a scope resolver

---

packages/button/CHANGELOG.md
packages/button/package.json
packages/carousel/CHANGELOG.md
packages/carousel/package.json
packages/hamburger/CHANGELOG.md
packages/hamburger/package.json
packages/icons/CHANGELOG.md
packages/icons/package.json
packages/slideshow/CHANGELOG.md
packages/slideshow/package.json
packages/utils/CHANGELOG.md
packages/utils/package.json

- @atlantis-lab/button@1.3.4
- @atlantis-lab/carousel@0.3.3
- @atlantis-lab/hamburger@0.1.0
- @atlantis-lab/icons@0.3.3
- @atlantis-lab/slideshow@0.3.3
- @atlantis-lab/utils@0.4.3

chore(release): %s

---

packages/carousel/src/SlideButton.tsx
packages/slideshow/package.json
packages/slideshow/src/Slices/Container.ts
packages/slideshow/src/Slices/Slice.ts
packages/slideshow/src/Slices/index.tsx
packages/slideshow/src/Slideshow.tsx
packages/slideshow/src/types.ts
yarn.lock

affects: @atlantis-lab/carousel, @atlantis-lab/slideshow

refactor(slideshow): add transition to slides

---

packages/slideshow/src/Slideshow.tsx

affects: @atlantis-lab/slideshow

refactor(slideshow): refactor styled props

---

packages/input/src/Checkbox.tsx

refactor(checkbox): add posibility to resize checkbox

---

packages/carousel/src/Carousel.tsx
packages/carousel/src/SlideButton.tsx
packages/carousel/src/types.ts
packages/icons/icons/arrow-left.svg
packages/icons/icons/arrow-right.svg

affects: @atlantis-lab/carousel, @atlantis-lab/icons

refactor(carousel): add squareControls, add overflow

---

packages/button/.storybook/main.js
packages/button/.storybook/preview.js
packages/button/package.json
packages/button/src/stories/Button.story.tsx
packages/carousel/.storybook/main.js
packages/carousel/.storybook/preview.js
packages/carousel/package.json
packages/carousel/src/stories/Carousel.story.tsx
packages/slideshow/.storybook/main.js
packages/slideshow/.storybook/preview.js
packages/slideshow/package.json
packages/slideshow/src/stories/Slideshow.story.tsx
packages/storybook/main.js
packages/storybook/package.json
packages/storybook/preview.js
yarn.lock

affects: @atlantis-lab/button, @atlantis-lab/carousel, @atlantis-lab/slideshow,
@atlantis-lab/storybook-config
- Moved config to packages/storybook
ISSUES CLOSED: #151

refactor: reinitialized storybook

---

packages/grid/src/stories/Grid.story.tsx

affects: @atlantis-lab/grid
ISSUES CLOSED: #150

feat(grid): add stories

---

packages/progress/src/Loading.tsx
packages/progress/src/stories/Loading.story.tsx

affects: @atlantis-lab/progress
- Also added "fill" prop to make Loading's color configurable
ISSUES CLOSED: #164

feat(progress): add story

---

packages/layout/src/stories/Column.story.tsx
packages/layout/src/stories/Layout.story.tsx
packages/layout/src/stories/Row.story.tsx

affects: @atlantis-lab/layout
ISSUES CLOSED: #162

feat(layout): add story

---

packages/grid/__tests__/Grid.test.tsx
packages/grid/__tests__/__snapshots__/Grid.test.tsx.snap
packages/grid/package.json
yarn.lock

affects: @atlantis-lab/grid
ISSUES CLOSED: #175

feat(grid): add test

---

packages/hamburger/__tests__/Hamburger.test.tsx
packages/hamburger/__tests__/__snapshots__/Hamburger.test.tsx.snap
packages/hamburger/package.json
yarn.lock

affects: @atlantis-lab/hamburger
ISSUES CLOSED: #177

feat(hamburger): add test

---

packages/icons-manager/__tests__/IconsManager.test.tsx
packages/icons-manager/__tests__/__snapshots__/IconsManager.test.tsx.snap
packages/icons-manager/package.json
yarn.lock

affects: @atlantis-lab/icons-manager
ISSUES CLOSED: #179

feat(icons-manager): add test

---

packages/layout/__tests__/Box.test.tsx
packages/layout/__tests__/Column.test.tsx
packages/layout/__tests__/Layout.test.tsx
packages/layout/__tests__/Row.test.tsx
packages/layout/__tests__/__snapshots__/Box.test.tsx.snap
packages/layout/__tests__/__snapshots__/Column.test.tsx.snap
packages/layout/__tests__/__snapshots__/Layout.test.tsx.snap
packages/layout/__tests__/__snapshots__/Row.test.tsx.snap
packages/layout/package.json
yarn.lock

affects: @atlantis-lab/layout
ISSUES CLOSED: #183

feat(layout): add test

---

packages/modal/__tests__/Modal.test.tsx
packages/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/modal/package.json

affects: @atlantis-lab/modal
ISSUES CLOSED: #185

feat(modal): add test

---

packages/slideshow/__tests__/__snapshots__/Slideshow.test.tsx.snap
packages/slideshow/src/Slideshow.tsx
packages/slideshow/src/stories/Slideshow.story.tsx

affects: @atlantis-lab/slideshow
- Also updated snapshot
ISSUES CLOSED: #167

fix(slideshow): fix margins

---

packages/carousel/__tests__/__snapshots__/Carousel.test.tsx.snap
packages/carousel/package.json
packages/carousel/src/Carousel.tsx
packages/carousel/src/stories/Carousel.story.tsx
yarn.lock

affects: @atlantis-lab/carousel
- Carousel is looped now
- Now carousel has animated horizontal overscroll
- Also updated
snapshot
ISSUES CLOSED: #113

feat(carousel): improve carousel

---

packages/icons-manager/__tests__/IconsManager.test.tsx
packages/icons-manager/src/IconsManager.tsx
packages/icons-manager/src/stories/IconsManager.story.tsx

affects: @atlantis-lab/icons-manager
ISSUES CLOSED: #202

refactor(icons-manager): change theme consuming logic

---

packages/background/__tests__/Background.test.tsx
packages/background/__tests__/__snapshots__/Background.test.tsx.snap
packages/background/package.json
packages/background/src/Background.ts
packages/background/src/index.ts
packages/background/src/stories/Background.story.tsx
yarn.lock

affects: @atlantis-lab/background
ISSUES CLOSED: #200

feat(background): add background component

---

packages/state/__tests__/__snapshots__/withState.test.tsx.snap
packages/state/__tests__/withState.test.tsx
packages/state/package.json

affects: @atlantis-lab/state
ISSUES CLOSED: #204

feat(state): add test

---

packages/design/package.json
packages/design/src/Container.ts
packages/design/src/Layout.ts
packages/design/src/List.ts
packages/design/src/Sample.tsx
packages/design/src/Space.tsx
packages/design/src/Text.ts
packages/design/src/index.ts
packages/design/tsconfig.build.json
yarn.lock

affects: @atlantis-lab/design
ISSUES CLOSED: #110

feat(design): create design package

---

packages/design/package.json
yarn.lock

fix(design): renaming package, add publishconfig

---

packages/background/__tests__/__snapshots__/Background.test.tsx.snap
packages/background/src/Background.ts
packages/background/src/stories/Background.story.tsx

affects: @atlantis-lab/background
ISSUES CLOSED: #215

feat(background): enhance background component

---

package.json
packages/theme/src/theme/borders.ts
packages/theme/src/theme/colors.ts
packages/theme/src/theme/fontFaces.ts
packages/theme/src/theme/fontSizes.ts
packages/theme/src/theme/fontWeights.ts
packages/theme/src/theme/fonts.ts
packages/theme/src/theme/lineHeights.ts
packages/theme/src/theme/radii.ts
packages/theme/src/theme/shadows.ts
yarn.lock

affects: @atlantis-lab/theme
actualy yarn.lock pushed

fix(theme): fix TS2695

---

package.json
packages/text/__tests__/Text.test.tsx
packages/text/__tests__/__snapshots__/Text.test.tsx.snap
packages/text/package.json
packages/text/src/SearchResult.tsx
packages/text/src/Space.tsx
packages/text/src/Text.ts
packages/text/src/index.ts
packages/text/src/stories/Text.story.tsx
packages/text/tsconfig.build.json
yarn.lock

affects: @atlantis-lab/state, @atlantis-lab/text

feat(text): add text component

---

packages/text/package.json

affects: @atlantis-lab/text
ISSUES CLOSED: #225

chore(text): add repository field in package.json

---

packages/theme/src/globals.ts
packages/theme/src/utils.ts

affects: @atlantis-lab/theme
- Added additional fontsPath prop in injectGlobalStyles
- Changed props order
ISSUES CLOSED: #237

fix(theme): change font operations flow

---

packages/theme/__tests__/theme/theme/borders.ts
packages/theme/__tests__/theme/theme/colors.ts
packages/theme/__tests__/theme/theme/fontFaces.ts
packages/theme/__tests__/theme/theme/fontSizes.ts
packages/theme/__tests__/theme/theme/fontWeights.ts
packages/theme/__tests__/theme/theme/fonts.ts
packages/theme/__tests__/theme/theme/lineHeights.ts
packages/theme/__tests__/theme/theme/radii.ts
packages/theme/__tests__/theme/theme/shadows.ts
packages/theme/src/index.ts

affects: @atlantis-lab/theme
- Also updated test
ISSUES CLOSED: #241

fix(theme): change theme types export method

---

packages/theme/__tests__/theme.test.tsx
packages/theme/__tests__/theme/Provider.ts
packages/theme/__tests__/theme/globals.ts
packages/theme/__tests__/theme/index.ts
packages/theme/__tests__/theme/theme/borders.ts
packages/theme/__tests__/theme/theme/colors.ts
packages/theme/__tests__/theme/theme/fontFaces.ts
packages/theme/__tests__/theme/theme/fontSizes.ts
packages/theme/__tests__/theme/theme/fontWeights.ts
packages/theme/__tests__/theme/theme/fonts.ts
packages/theme/__tests__/theme/theme/lineHeights.ts
packages/theme/__tests__/theme/theme/radii.ts
packages/theme/__tests__/theme/theme/shadows.ts
packages/theme/package.json
packages/theme/src/utils.ts

affects: @atlantis-lab/theme
ISSUES CLOSED: #237

fix(theme): change fonts path's resolve method

---

packages/input/__tests__/Input.test.tsx
packages/input/__tests__/PriceInput.test.tsx
packages/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/input/__tests__/__snapshots__/PriceInput.test.tsx.snap
packages/input/src/parts/Addon.tsx
packages/input/src/parts/StyledInput.tsx

affects: @atlantis-lab/input
ISSUES CLOSED: #254

refactor(input): change theme consuming logic

---

packages/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/input/__tests__/__snapshots__/PriceInput.test.tsx.snap
packages/input/src/parts/Addon.tsx
packages/input/src/parts/Addons.tsx
packages/input/src/parts/StyledInput.tsx
packages/input/src/parts/index.ts

affects: @atlantis-lab/input
ISSUES CLOSED: #256

fix(input): theme consuming

---

packages/link/__tests__/Link.test.tsx
packages/link/__tests__/NextLink.test.tsx
packages/link/__tests__/RouteLink.test.tsx
packages/link/__tests__/__snapshots__/Link.test.tsx.snap
packages/link/__tests__/__snapshots__/NextLink.test.tsx.snap
packages/link/__tests__/__snapshots__/RouteLink.test.tsx.snap
packages/link/package.json
packages/link/src/Link.tsx
packages/link/src/LinkUI.tsx
packages/link/src/NextLink.tsx
packages/link/src/RouteLink.tsx
packages/link/src/index.ts
packages/link/src/stories/Link.story.tsx
packages/link/src/stories/NextLink.story.tsx
packages/link/src/stories/RouteLink.story.tsx
packages/link/src/types.ts
packages/link/tsconfig.build.json
yarn.lock

affects: @atlantis-lab/link
ISSUES CLOSED: #250

feat(link): init link

---

packages/input/__tests__/Checkbox.test.tsx
packages/input/__tests__/Input.test.tsx
packages/input/__tests__/PriceInput.test.tsx
packages/input/__tests__/Textarea.test.tsx
packages/input/package.json
packages/input/src/Textarea.tsx
packages/input/src/parts/Addon.tsx
packages/input/src/parts/Addons.tsx
packages/input/src/parts/StyledInput.tsx
packages/input/src/parts/index.ts
packages/input/src/stories/Checkbox.story.tsx
packages/input/src/stories/Input.story.tsx
packages/input/src/stories/PriceInput.story.tsx
packages/link/__tests__/Link.test.tsx
packages/link/__tests__/NextLink.test.tsx
packages/link/__tests__/RouteLink.test.tsx
packages/link/package.json
packages/link/src/Link.tsx
packages/link/src/LinkUI.tsx
packages/link/src/NextLink.tsx
packages/link/src/RouteLink.tsx
packages/link/src/stories/Link.story.tsx
packages/link/src/stories/NextLink.story.tsx
packages/link/src/stories/RouteLink.story.tsx
packages/storybook/package.json
packages/storybook/src/preview.js
yarn.lock

affects: @atlantis-lab/storybook
ISSUES CLOSED: #258

chore(storybook): replace ThemeProvider

---

packages/background/package.json
packages/button/package.json
packages/button/src/stories/Button.story.tsx
packages/carousel/__tests__/Carousel.test.tsx
packages/carousel/package.json
packages/carousel/src/Carousel.tsx
packages/carousel/src/stories/Carousel.story.tsx
packages/design/package.json
packages/grid/package.json
packages/hamburger/package.json
packages/icons-manager/__tests__/IconsManager.test.tsx
packages/icons-manager/package.json
packages/icons-manager/src/IconsManager.tsx
packages/icons-manager/src/stories/IconsManager.story.tsx
packages/icons/package.json
packages/input/package.json
packages/layout/package.json
packages/link/package.json
packages/modal/package.json
packages/progress/package.json
packages/select/package.json
packages/slideshow/package.json
packages/slideshow/src/Dots/index.tsx
packages/state/package.json
packages/storybook/package.json
packages/text/package.json
packages/theme/package.json
packages/utils/package.json
yarn.lock

affects: @atlantis-lab/button, @atlantis-lab/carousel, @atlantis-lab/icons-manager,
@atlantis-lab/slideshow
ISSUES CLOSED: #274

fix: theme consuming logic

---

.pnp.js
ui-parts/text/package.json
ui-parts/text/src/currency.component.tsx
ui-parts/text/src/currency.interface.ts
ui-proto/text/src/currency.stories.tsx
yarn.lock

- Added stories for currency
ISSUES CLOSED: #322

fix: currency types

---

ui-parts/button/package.json
ui-proto/button/package.json
yarn.lock

- Апгрейд `peerDependencies` в  `ui-parts/button` и `ui-proto/button`

Chore/update button peerDependencies

---

utils/use-hover/src/index.ts
utils/use-hover/src/use-hover.hook.ts
utils/use-popover/src/index.ts
utils/use-popover/src/use-popover.hook.ts

Данный pr, создан для триггера релиза, после добавления нужного скоупа.

fix: added new scope for publication

---

ui-parts/checkbox/src/container/base/base.styles.ts

Сделал изменение в коде, чтобы пересобрать и запаблить пакет.

chore(checkbox): update code to publish package

---

.pnp.cjs
utils/use-popover/package.json
yarn.lock

- добавлена дев зависимость csstype
- повышена патч версия

fix: add-missing-dependence-utils-use-popover

---

ui-parts/next-image/src/index.ts
ui-parts/next-image/src/next-image.component.tsx
ui-parts/next-image/src/next-image.interfaces.ts

feat: next-image-props

---

.yarn/versions/3095e196.yml
ui-admin/theme/package.json
ui-parts/theme/package.json

Публикация пакетов с темой
Источник: https://github.com/rees46/planning/issues/1498#issuecomment-2310749476

chore(common): publish theme packages

---

utils/use-popover/package.json
utils/use-popover/src/use-popover.hook.ts

closes https://github.com/atls/hyperion/issues/587
- версию пакета поднял.
- этого же достаточно, чтобы пакет обновился на npm?

fix(utils): use-popover

---

generators/appearance/package.json
generators/appearance/src/appearance-style/appearance-style.generator.ts
generators/appearance/src/appearance-style/tests/appearance-styles.generator.test.constants.ts
generators/icons/package.json
generators/icons/src/replacement-utils/create-replacements/create-replacements.util.cts
generators/icons/src/replacement-utils/create-replacements/index.cts
generators/icons/src/replacement-utils/create-replacements/tests/create-replacements.test.constants.ts
generators/icons/src/replacement-utils/get-color-replacement/get-color-replacement.util.cts
generators/icons/src/replacement-utils/get-color-replacement/get-color-replacement.util.ts
generators/icons/src/replacement-utils/get-color-replacement/index.cts
generators/icons/src/replacement-utils/get-color-replacement/tests/get-color-replacement.test.ts
generators/icons/src/replacement-utils/index.cts
generators/icons/src/svgr-utils/compile-icons.util.ts
generators/utils/src/process-file.util.ts

Closes https://github.com/atls/hyperion/issues/601

fix(generators): errors

---

generators/icons/package.json

Предыдущий publish упал:
https://github.com/atls/hyperion/actions/runs/13850236016/job/38756197680

chore(icons): trigger npm publish

---

.pnp.cjs
package.json
ui-admin/design/src/index.ts
ui-parts/design/src/index.ts
ui-parts/text-transform/package.json
ui-parts/text-transform/src/tests/text-transofrm.test.tsx
ui/design/package.json
ui/design/src/constants.ts
ui/design/src/main.ts
yarn.lock

Closes https://github.com/atls/hyperion/issues/604
https://ui-admin.ui.atls.design
https://ui-parts.ui.atls.design

fix(atls-ui): fallback urls

---

generators/icons/src/svgr-utils/compile-icons.util.ts

Запрос от https://github.com/rees46/web-app/pull/25#issue-2983579747

refactor(icons): remove FC type from icon template

---

ui-parts/button/src/utils/create-shape-styles/create-shape-styles.interfaces.ts

Resolves https://github.com/atls/hyperion/issues/612

feat(atls-ui-parts): update create-shape-styles interfaces

---

generators/icons/package.json

Прошлый PR https://github.com/atls/hyperion/pull/618 упал

chore(common): trigger release
